### ISSUE TITLE
Short Extion support

### ISSUE THREAD

**Issue by choman** [marcelm/xopen#29]
It would be nice if the following extensions were recognized for reading and writing:
- .tgz
- .tbz2
- .txv

**Comment by marcelm** [comment]
Hi, thanks for the suggestion, but I believe the focus of this project should be more on opening single, compressed files, not archives. So adding Zstd, Brotli etc. would be interesting, but not zip, tar, rar, 7-zip etc.

Or do you simply want to be able to xopen a `.tgz` file and have it recognized as a gzip-compressed file? (And using the `tarfile` module yourself to access the archive contents.) That should actually already work at the moment, at least for reading, since we don’t look at the file name extension anymore, but inspect the file content to detect the compression format.

cf #27

**Comment by marcelm** [comment]
Closing this for the moment. With version 0.9.0 that is about to be released, you’ll be able to open `.tgz` files and have them recognized as gzip-compressed files, but as I said, opening archives is not the focus of this project.
