### ISSUE TITLE
Error 'PipedGzipReader' object is not an iterator.

### ISSUE THREAD

**Issue by alexandrefassio** [marcelm/xopen#30]
When reading a .gz file with threads, it returns a PipedGzipReader as expected. However, if one tries to loop over it using next() for example, it raises the error 'PipedGzipReader' object is not an iterator.

It could be fixed by implementing __next__() in the PipedGzipReader class. Maybe you could implement something like the below example:

def __next__(self):
      self.readline()

**Comment by marcelm** [comment]
This should actually work. Can you please ensure that you use the most recent xopen version and, if you still see the problem, give a short, self-contained example that shows the problem? (And let me know which Python version you use.)

This works in Python 3.6+:
```python
from xopen import xopen
with xopen("tests/file.txt.gz", threads=2) as f:
  for line in f:
    print(line)
```

**Comment by alexandrefassio** [comment]
I downloaded xopen directly from conda just today. So I guess it is updated. In fact, if I use "for line in f:" as you mentioned it indeed works. But if I call next() it breaks.

My code looks like this:

with xopen(my_file, "r") as IN:
     while True:
           try:
                line = next(IN)
                ...
            except StopIteration:
                 ...

Then I manually implemented

**Comment by marcelm** [comment]
Thanks for the example. Yes, you’re right: `PipedGzipReader` objects support iteration, that is, they implement `__iter__`, but they are not iterators themselves (that is, they do not implement `__next__`). The code above will work if you change the beginning to
```python
with xopen(my_file) as infile:
  it = iter(infile)
  while True:
    try:
      line = next(it)
...
```
Note that you should normally not handle the `StopIteration` manually as you do here, but use a `for` loop, which will do that for you. It will also call `iter()` for you, which is why `for line in f:` in the example I gave works.

However, it appears as if all the other file-like objects (GzipFile, Bz2File etc.) *do* implement `__next__`, so I’ll add this to `PipedGzipReader` as well to make it more compatible.

Thanks for the report!

**Comment by rhpvorderman** [comment]
For extra context.

Every filehandle is an iterator in the python language. The `__iter__` method of PipedGzipReader returns this filehandle. The `__next__` method for filehandles is implemented in C. Hence it is very fast.

A `__next__` method on PipedGzipReader would probable by implemented as `next(self._file)` or `self._file.__next__`. This will have implications for performance. `PipedGzipReader.__next__` will call `self._file.__next__`. While if you use the `iter()` function you get access to the filehandle directly. If you use the filehandle in a for loop, (without using next) this will eliminate the need for two function lookups for every line you read from the file compared to calling the next method on PipedGzipReader.
