### ISSUE TITLE
Error reading FastQ files via multiprocessing?

### ISSUE THREAD

**Issue by ayaanhossain** [marcelm/xopen#31]
Hello, I have the following script `xopen_test.py` which simply reads the content of a `filename` and prints it out. Unfortunately, when the files are gzipped (via `pigz`) only a few of the first thousand lines are printed (first 700 or so reads), and the script terminates without any error. This leads to partial processing of the full file.

```
import xopen
import multiprocessing as mp

def stream_reads(filename):
    for i,string in enumerate(xopen.xopen(filename, 'rt')):
        print(filename, i, string.strip())

def test_process():

    readfile1='PE_Reads1.fq.gz'
    readfile2='PE_Reads2.fq.gz'

    procs = []
    for filename in [readfile1, readfile2]:
        proc = mp.Process(target=stream_reads, args=(filename,))
        procs.append(proc)
        proc.start()
    
    for proc in procs:
        proc.join()

def test_pool():

    readfile1='PE_Reads1.fq.gz'
    readfile2='PE_Reads2.fq.gz'

    pool = mp.Pool(2)
    pool.map(stream_reads, (readfile1, readfile2))

if __name__ == '__main__':
    test_process()
    # test_pool()
```
Happy to share any further information, but I have been able to reproduce this with a couple of my FastQ files, both real and synthetic, gzipped with both `pigz` and `gzip`. There is no error if the files are not zipped, i.e. program runs fine in multiprocessing, on the equivalent `.fq` files. 

Thanks, Ayaan

**Comment by marcelm** [comment]
Thanks for the report! While I ran your code, I actually came across another issue that needed fixing. It also turned out that I was able to reproduce your problem with version 0.8.4, but no longer with the current master. I’m not quite sure which change fixed it, but the problem should no longer exist.

I have now released version 0.9.0, which should work as expected.

By the way, if you want to efficiently open FASTQ files, you could use [dnaio](https://pypi.org/project/dnaio/), which is the library I use in Cutadapt. (It’s faster than many other FASTQ parsers.)

Thanks again! Please let me know if your problem persists.

**Comment by ayaanhossain** [comment]
Thank you Marc! I can confirm the issue no longer exists with v0.9.0. I will checkout dnaio, thanks for the tip!

**Comment by marcelm** [comment]
Perfect :-)
